### ISSUE TITLE
Please change the comma in api.py to ascii

### ISSUE THREAD

**Issue by donotevercry** [aliyun/aliyun-oss-python-sdk#142]
Got this error with the new 2.6.0 release:
2018-11-21 11:46:50,544: api        INFO     Start to get object, bucket: xxxx\uff0c key: xxxx, range: , headers: {}, params: {}
--- Logging error ---
Traceback (most recent call last):
  File "/home/tops/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\uff0c' in position 96: ordinal not in range(128)
Call stack:
  File "/home/tops/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)

---> The reason is someone put a chinese comma(non ascii) in the logging:
logger.info("Start to get object, bucket: {0}， key: {1}, range: {2}, headers: {3}, params: {4}".format(
            self.bucket_name, to_string(key), range_string, headers, params))

**Comment by coderall** [comment]
do you ever modify the api.py file? @donotevercry

**Comment by hangzws** [comment]
yes, there a chinese comma int the logging, but i do not think it cause the exception but the bucket name.
