### ISSUE TITLE
oss2.resumable_upload()方法在python2.7版本运行报错

### ISSUE THREAD

**Issue by DingGuodong** [aliyun/aliyun-oss-python-sdk#146]
Python 版本：Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] on win32
当上传的文件路径包含中文字符时（filename 为unicode类型），会提示：
```  File "C:\Python27\lib\site-packages\oss2\resumable.py", line 69, in resumable_upload
    size = os.path.getsize(filename)
  File "C:\Python27\lib\genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
WindowsError: [Error 123]` : 'C:\xxxx
```

**Comment by hangzws** [comment]
建议使用utf-8编码

**Comment by DingGuodong** [comment]
@hangzws 感谢回复，但我的代码里到报错行前已经是utf-8编码了。我把代码和报错都附上，请帮忙看一下。

代码如下：

```
import os
import oss2
import json

with open('config.json') as fp:
    info = fp.read()
    ak = json.loads(info)["access_key"][0]
    bucket_info = json.loads(info)["bucket_info"][0]

access_key_id = os.getenv('OSS_TEST_ACCESS_KEY_ID', ak.get('AccessKeyID'))
access_key_secret = os.getenv('OSS_TEST_ACCESS_KEY_SECRET', ak.get('AccessKeySecret'))
bucket_name = os.getenv('OSS_TEST_BUCKET', bucket_info.get('name'))
endpoint = os.getenv('OSS_TEST_ENDPOINT', bucket_info.get('endpoint'))

bucket = oss2.Bucket(oss2.Auth(access_key_id, access_key_secret), endpoint, bucket_name)


def to_unicode_or_bust(obj, encoding='utf-8'):
    # the function convert non-unicode object to unicode object
    if isinstance(obj, basestring):
        if not isinstance(obj, unicode):
            obj = unicode(obj, encoding)

    return obj


# D:\C盘桌面未整理\EBT\测试视频\仔细阅读合同条款远离裸贷信贷.mp4
# C:\Users\Guodong\Desktop\test_video.mp4
filename = to_unicode_or_bust(raw_input("Input file path going to upload:"))  # got <type 'unicode'>
if not os.path.exists(filename):  # need <type 'unicode'>
    print("No such file or directory")
else:
    print("File %s selected." % filename)

key = os.path.basename(filename)

# SDK in python2 using str(in py3 is bytes) type with 'utf-8' encoded, so we need convert unicode into str
filename = oss2.to_bytes(filename)
key = oss2.to_bytes(key)

print(type(filename), type(key))

oss2.resumable_upload(bucket, key, filename, multipart_threshold=100 * 1024)

print(bucket.get_object(key))
```

之后后报错如下：

```
2018-12-19 15:45:59,641 oss2.api [INFO] 15912 : Init oss bucket, endpoint: oss-cn-hangzhou.aliyuncs.com, isCname: False, connect_timeout: None, app_name: , enabled_crc: True
Input file path going to upload:D:\C盘桌面未整理\EBT\测试视频\仔细阅读合同条款远离裸贷信贷.mp4
File D:\C盘桌面未整理\EBT\测试视频\仔细阅读合同条款远离裸贷信贷.mp4 selected.
(<type 'str'>, <type 'str'>)
2018-12-19 15:47:35,845 oss2.resumable [INFO] 15912 : Start to resumable upload, bucket: dlah-rescloud, key: 仔细阅读合同条款远离裸贷信贷.mp4, filename: D:\C盘桌面未整理\EBT\测试视频\仔细阅读合同条款远离裸贷信贷.mp4, headers: None, multipart_threshold: 102400, part_size: None, num_threads: None
Traceback (most recent call last):
  File "C:/Users/Guodong/PycharmProjects/LinuxBashShellScriptForOps/projects/others/aliyun/OSS/oss-upload-demo/upload_test.py", line 70, in <module>
    oss2.resumable_upload(bucket, key, filename, multipart_threshold=100 * 1024)
  File "C:\Python27\lib\site-packages\oss2\resumable.py", line 69, in resumable_upload
    size = os.path.getsize(filename)
  File "C:\Python27\lib\genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
WindowsError: [Error 3] : 'D:\\C\xe7\x9b\x98\xe6\xa1\x8c\xe9\x9d\xa2\xe6\x9c\xaa\xe6\x95\xb4\xe7\x90\x86\\EBT\\\xe6\xb5\x8b\xe8\xaf\x95\xe8\xa7\x86\xe9\xa2\x91\\\xe4\xbb\x94\xe7\xbb\x86\xe9\x98\x85\xe8\xaf\xbb\xe5\x90\x88\xe5\x90\x8c\xe6\x9d\xa1\xe6\xac\xbe\xe8\xbf\x9c\xe7\xa6\xbb\xe8\xa3\xb8\xe8\xb4\xb7\xe4\xbf\xa1\xe8\xb4\xb7.mp4'

Process finished with exit code 1
```

在debug模式下，编码是utf-8的，type为str，因此，请帮忙核查一下原因。谢谢！

**Comment by hangzws** [comment]
我这边环境没有这样的的问题，能否提供一下环境给我们？

**Comment by DingGuodong** [comment]
我在一开始提供了python环境，Python 版本：Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] on win32。请问还需要提供什么信息呢？

**Comment by liyanzhang505** [comment]
filename = oss2.to_bytes(filename)，把这段代码注释掉

**Comment by DingGuodong** [comment]
> filename = oss2.to_bytes(filename)，把这段代码注释掉

@liyanzhang505 感谢回复，但并不好用，依旧存在UnicodeEncodeError错误。

**Comment by liyanzhang505** [comment]
@DingGuodong 我重新测了一下，你需要把filename = oss2.to_bytes(filename)、to_unicode_or_bust调用都去掉，python3用input，python2.7用raw_input，如下：filename = raw_input("Input file path going to upload:")

**Comment by DingGuodong** [comment]
@liyanzhang505 感谢回复，但依旧不好用，代码如下：
```python
import os
import oss2
import json

with open('config.json') as fp:
    info = fp.read()
    ak = json.loads(info)["access_key"][0]
    bucket_info = json.loads(info)["bucket_info"][0]

access_key_id = os.getenv('OSS_TEST_ACCESS_KEY_ID', ak.get('AccessKeyID'))
access_key_secret = os.getenv('OSS_TEST_ACCESS_KEY_SECRET', ak.get('AccessKeySecret'))
bucket_name = os.getenv('OSS_TEST_BUCKET', bucket_info.get('name'))
endpoint = os.getenv('OSS_TEST_ENDPOINT', bucket_info.get('endpoint'))

bucket = oss2.Bucket(oss2.Auth(access_key_id, access_key_secret), endpoint, bucket_name)


def to_unicode_or_bust(obj, encoding='utf-8'):
    # the function convert non-unicode object to unicode object
    if isinstance(obj, basestring):
        if not isinstance(obj, unicode):
            obj = unicode(obj, encoding)

    return obj


# D:\C盘桌面未整理\EBT\测试视频\仔细阅读合同条款远离裸贷信贷.mp4
# C:\Users\Guodong\Desktop\test_video.mp4
filename = raw_input("Input file path going to upload:")
if not os.path.exists(filename):  # need <type 'unicode'>
    print("No such file or directory")
else:
    print("File %s selected." % filename)

key = os.path.basename(filename)

# SDK in python2 using str(in py3 is bytes) type with 'utf-8' encoded, so we need convert unicode into str
# filename = oss2.to_bytes(filename)
key = oss2.to_bytes(key)

print(type(filename), type(key))

oss2.resumable_upload(bucket, key, filename, multipart_threshold=100 * 1024)

print(bucket.get_object(key))
```
运行结果如下：
```
C:\Python27\python.exe C:/Users/Guodong/PycharmProjects/LinuxBashShellScriptForOps/projects/others/aliyun/OSS/oss-upload-demo/upload_test_issued.py
Input file path going to upload:D:\C盘桌面未整理\EBT\测试视频\仔细阅读合同条款远离裸贷信贷.mp4
Traceback (most recent call last):
  File "C:/Users/Guodong/PycharmProjects/LinuxBashShellScriptForOps/projects/others/aliyun/OSS/oss-upload-demo/upload_test_issued.py", line 70, in <module>
    oss2.resumable_upload(bucket, key, filename, multipart_threshold=100 * 1024)
  File "C:\Python27\lib\site-packages\oss2\resumable.py", line 69, in resumable_upload
    size = os.path.getsize(filename)
  File "C:\Python27\lib\genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
WindowsError: [Error 3] : 'D:\\C\xe7\x9b\x98\xe6\xa1\x8c\xe9\x9d\xa2\xe6\x9c\xaa\xe6\x95\xb4\xe7\x90\x86\\EBT\\\xe6\xb5\x8b\xe8\xaf\x95\xe8\xa7\x86\xe9\xa2\x91\\\xe4\xbb\x94\xe7\xbb\x86\xe9\x98\x85\xe8\xaf\xbb\xe5\x90\x88\xe5\x90\x8c\xe6\x9d\xa1\xe6\xac\xbe\xe8\xbf\x9c\xe7\xa6\xbb\xe8\xa3\xb8\xe8\xb4\xb7\xe4\xbf\xa1\xe8\xb4\xb7.mp4'
No such file or directory
(<type 'str'>, <type 'str'>)

Process finished with exit code 1
```

**Comment by liyanzhang505** [comment]
@DingGuodong 你现在报的错是因为你运行的upload_test_issued.py这个文件不是UTF8无BOM格式。我这里用其他格式编码是报你一样的错误。你检查一下你的文件编码格式。

**Comment by DingGuodong** [comment]
@liyanzhang505 感谢回复，但实际上我运行的这个文件的确是UTF-8格式的。
```bash
$ file upload_test_issued.py 
upload_test_issued.py: Python script, UTF-8 Unicode text executable
```
你刚才的这条回复我没有看明白，你那边用我上面附上的代码，可以运行成功吗？

**Comment by liyanzhang505** [comment]
@DingGuodong你linux环境加上# -*- coding: utf-8 -*-，windows，你用Notepad++打开，看下格式。

**Comment by DingGuodong** [comment]
@liyanzhang505 感谢回复，我用了notepad++，的确是UTF-8，没有错的。

**Comment by liyanzhang505** [comment]
@DingGuodong 我运行的就是你贴的这段代码，去掉filename = oss2.to_bytes(filename)、to_unicode_or_bust这两个调用之后，我这这里只有文件编码不对的时候才会报你同样的错误，linux/windows我都试了。你尝试新建一个文件试试。

**Comment by DingGuodong** [comment]
@liyanzhang505 感谢回复，你在输入文件路径时，是用的中文路径吗？比如我用的输入是“D:\C盘桌面未整理\EBT\测试视频\仔细阅读合同条款远离裸贷信贷.mp4”，用英文的是没问题的。

**Comment by liyanzhang505** [comment]
@DingGuodong 是用中文路径中文名称测试的。

**Comment by liyanzhang505** [comment]
跟你贴的的代码，唯一不一样的就是我加了`# -*- coding: utf-8 -*-` 你试下？

**Comment by DingGuodong** [comment]
@liyanzhang505 那真是奇怪了。我这儿也是有这行注释的。现在看来oss2和我安装的python2.7中的os和sys模块有冲突。要么os.path.下的方法好用，要么oss2下的一些方法不好用。还是放弃2.7，用3吧。

**Comment by hangzws** [comment]
看起来是你的python环境问题，你尝试换个环境试了没?

**Comment by DingGuodong** [comment]
@hangzws 我用新的电脑新建了一个环境，问题有点转机，但还是报错：
环境：```
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] on win32
```
代码：```
# -*- coding: utf-8 -*-
import os
import oss2
import json

with open('config.json') as fp:
    info = fp.read()
    ak = json.loads(info)["access_key"][0]
    bucket_info = json.loads(info)["bucket_info"][0]

access_key_id = os.getenv('OSS_TEST_ACCESS_KEY_ID', ak.get('AccessKeyID'))
access_key_secret = os.getenv('OSS_TEST_ACCESS_KEY_SECRET', ak.get('AccessKeySecret'))
bucket_name = os.getenv('OSS_TEST_BUCKET', bucket_info.get('name'))
endpoint = os.getenv('OSS_TEST_ENDPOINT', bucket_info.get('endpoint'))

bucket = oss2.Bucket(oss2.Auth(access_key_id, access_key_secret), endpoint, bucket_name)


def to_unicode_or_bust(obj, encoding='utf-8'):
    # the function convert non-unicode object to unicode object
    if isinstance(obj, basestring):
        if not isinstance(obj, unicode):
            obj = unicode(obj, encoding)

    return obj


# D:\C盘桌面未整理\EBT\测试视频\仔细阅读合同条款远离裸贷信贷.mp4
# C:\Users\Guodong\Desktop\test_video.mp4
filename = raw_input("Input file path going to upload:")
if not os.path.exists(filename):  # need <type 'unicode'>
    print("No such file or directory")
else:
    print("File %s selected." % filename)

key = filename.split("\\")[-1]

# SDK in python2 using str(in py3 is bytes) type with 'utf-8' encoded, so we need convert unicode into str
# filename = oss2.to_bytes(filename)
# key = oss2.to_bytes(key)

print(type(filename), type(key))

oss2.resumable_upload(bucket, key, filename, multipart_threshold=100 * 1024)

print(bucket.get_object(key))
```
运行结果：```
C:\Users\chris.ding\Desktop\python>execd.py
C:\Python27\lib\site-packages\aliyunsdkcore\vendored\requests\packages\urllib3\c
ontrib\socks.py:37: DependencyWarning: SOCKS support in urllib3 requires the ins
tallation of optional dependencies: specifically, PySocks.  For more information
, see https://urllib3.readthedocs.io/en/latest/contrib.html#socks-proxies
  DependencyWarning
Input file path going to upload:C:\Users\chris.ding\Desktop\python\测试视频\仔细
阅读合同条款远离裸贷信贷.mp4
File C:\Users\chris.ding\Desktop\python\测试视频\仔细阅读合同条款远离裸贷信贷.mp
4 selected.
(<type 'str'>, <type 'str'>)
No handlers could be found for logger "oss2.api"
Traceback (most recent call last):
  File "C:\Users\chris.ding\Desktop\python\execd.py", line 44, in <module>
    oss2.resumable_upload(bucket, key, filename, multipart_threshold=100 * 1024)

  File "C:\Python27\lib\site-packages\oss2\resumable.py", line 79, in resumable_
upload
    result = uploader.upload()
  File "C:\Python27\lib\site-packages\oss2\resumable.py", line 450, in upload
    self.__load_record()
  File "C:\Python27\lib\site-packages\oss2\resumable.py", line 522, in __load_re
cord
    upload_id = self.bucket.init_multipart_upload(self.key, headers=self.__heade
rs).upload_id
  File "C:\Python27\lib\site-packages\oss2\api.py", line 1020, in init_multipart
_upload
    resp = self.__do_object('POST', key, params={'uploads': ''}, headers=headers
)
  File "C:\Python27\lib\site-packages\oss2\api.py", line 1590, in __do_object
    return self._do(method, self.bucket_name, key, **kwargs)
  File "C:\Python27\lib\site-packages\oss2\api.py", line 210, in _do
    raise e
oss2.exceptions.InvalidArgument: {'status': 400, 'x-oss-request-id': '5C63998CBB
40975F5A7D87A6', 'details': {'Message': 'The characters encoding must be utf-8.'
, 'Code': 'InvalidArgument'}}
```
看起来应该还是哪里编码的问题。

**Comment by hangzws** [comment]
传入的key不是utf-8编码，你那个to_bytes的注释打开试下，或者换成to_string。

**Comment by DingGuodong** [comment]
@hangzws 试过了，无论是将key做to_bytes还是to_string，都是报错。

**Comment by hangzws** [comment]
排查是否是环境问题吧，我们这边都是ok的。

**Comment by DingGuodong** [comment]
@hangzws 跟Windows环境和cmd里面（cmd粘贴进去的编码默认实际上是gbk）执行有关系吗？我试过PyCharm（执行环境是utf-8）和Python自带的IDLE（执行环境是cmd里），都不行。

**Comment by liyanzhang505** [comment]
@DingGuodong 我这里确认了一下，windows 环境下python2.7.15默认编码是ascii，所以你代码里要filename.decode('gbk').encode('utf8')。另外SDK里resumable_upload函数也有问题， os.path.getsize(filename)，os.path.getmtime(filename)  这两个地方filename需要to_unicode转换。所以你这个环境下确实会有你这个问题。你可以尝试安装python3或者下载SDK改下那两处重新安装。

**Comment by DingGuodong** [comment]
感谢回复和做了这么多的工作。那看来的确是SDK的函数问题了。眼下Python2快停止支持了，抛开此SDK来说，的确有必要升级到Python3了。

**Comment by hangzws** [comment]
谢谢发现问题，python2的版本我们还是要继续支持。下个版本我们要fix这个问题。
