### ISSUE TITLE
import oss2时报错：cannot import name b64decode_from_string

### ISSUE THREAD

**Issue by wx7in7** [aliyun/aliyun-oss-python-sdk#150]
Python 2.7.14 |Anaconda, Inc.| (default, Mar 27 2018, 17:29:31) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import oss2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pysdk/wangxiang/demo/ENV/lib/python2.7/site-packages/oss2/__init__.py", line 3, in <module>
    from . import models, exceptions
  File "/home/pysdk/wangxiang/demo/ENV/lib/python2.7/site-packages/oss2/models.py", line 10, in <module>
    from .utils import http_to_unixtime, make_progress_adapter, make_crc_adapter
  File "/home/pysdk/wangxiang/demo/ENV/lib/python2.7/site-packages/oss2/utils.py", line 30, in <module>
    from Crypto.Cipher import AES
  File "/home/pysdk/wangxiang/demo/ENV/lib/python2.7/site-packages/oss2/Crypto.py", line 12, in <module>
    from oss2.utils import b64decode_from_string, b64encode_as_string
ImportError: cannot import name b64decode_from_string

**Comment by dk-star** [comment]
how to resolve this error ?
