### ISSUE TITLE
下载出现IncompleteRead from source

### ISSUE THREAD

**Issue by xiaogaoer** [aliyun/aliyun-oss-python-sdk#162]
走的是外网，下载过程偶尔出现 IncompleteRead from source，具体错误栈：
![image](https://user-images.githubusercontent.com/15725262/53412374-32ea3200-3a04-11e9-8371-e1cc315a0661.png)
请问是怎么搞

**Comment by coderall** [comment]
把 request id 等错误 发给相关客服或售后看下

**Comment by jianlong-yuan** [comment]
当使用开多进程的时候，这种情况发生概率很高，请问下可以根本性解决吗？

**Comment by SimZhou** [comment]
同样的问题，文件量较大的时候，有时候会报错。重新dvc pull一次，就好了。

**Comment by SimZhou** [comment]
这个应该是dvc的问题，不是oss这边的问题（大概），但是很奇怪没有搜到别的地方有人出这个问题。可能是用户基数太少bug还不够？也可能是很少有人会同时上传很多文件？也可能是别人用gdrive不会出这个问题但是oss会出这个问题（这种情况下就是oss的问题了）？

**Comment by SimZhou** [comment]
找到一个解决方法，下载数据时使用单线程：
```bash
dvc pull -j 1
```
即可大概率解决这个问题。

FYI:
dvc默认使用4 * cpu核心数个线程同时下载文件，也就是如果8核处理器就会同时下载32个文件。
```
# dvc pull --help
usage: dvc pull [-h] [-q | -v] [-j <number>] [-r <name>] [-a] [-T] [--all-commits] [-f] [-d] [-R] [--run-cache]         
                [targets [targets ...]]                                                                                 
                                                                                                                        
Download tracked files or directories from remote storage.                                                              
Documentation: <https://man.dvc.org/pull>                                                                               
                                                                                                                        
positional arguments:                                                                                                   
  targets               Limit command scope to these tracked files/directories, .dvc files, or stage names.             
                                                                                                                        
optional arguments:                                                                                                     
  -h, --help            show this help message and exit                                                                 
  -q, --quiet           Be quiet.                                                                                       
  -v, --verbose         Be verbose.                                                                                     
  -j <number>, --jobs <number>                                                                                          
                        Number of jobs to run simultaneously. The default value is 4 * cpu_count(). For SSH remotes,    
                        the default is 4.                                                                               
  -r <name>, --remote <name>                                                                                            
                        Remote storage to pull from                                                                     
  -a, --all-branches    Fetch cache for all branches.
  -T, --all-tags        Fetch cache for all tags.                                                                       
  --all-commits         Fetch cache for all commits.
  -f, --force           Do not prompt when removing working directory files.
  -d, --with-deps       Fetch cache for all dependencies of the specified target.
  -R, --recursive       Pull cache for subdirectories of the specified directory.
  --run-cache           Fetch run history for all stages.
```

**Comment by guozenghuang** [comment]
1. 同一个环境下，使用断点续传下载大文件，只要有进行分片也会有类似错误

```python
oss2.resumable_download(buck, key, filename ,store=oss2.ResumableDownloadStore(root='/tmp'),multiget_threshold=20 * 1024 * 1024,part_size=10 * 1024 * 1024,num_threads=2)
```

```
An exception was thrown by producer or consumer, backtrace: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/oss2/task_queue.py", line 76, in __consumer_func
    consumer(self)
  File "/usr/local/lib/python3.6/site-packages/oss2/resumable.py", line 410, in __consumer
    self.__download_part(part)
  File "/usr/local/lib/python3.6/site-packages/oss2/resumable.py", line 425, in __download_part
    utils.copyfileobj_and_verify(result, f, part.end - part.start, request_id=result.request_id)
  File "/usr/local/lib/python3.6/site-packages/oss2/utils.py", line 863, in copyfileobj_and_verify
    raise InconsistentError("IncompleteRead from source", request_id)
oss2.exceptions.InconsistentError: {'status': -3, 'x-oss-request-id': '61DBDAB122F64B3231EFDB45', 'details': 'InconsistentError: IncompleteRead from source'}

ERROR: {'status': -3, 'x-oss-request-id': '61DBDAB122F64B3231EFDB45', 'details': 'InconsistentError: IncompleteRead from source'}
```

2. 而如果不使用分片下载，则不会报错。
```python
oss2.resumable_download(buck, key, filename ,store=oss2.ResumableDownloadStore(root='/tmp'))
```

- 这种情况有解吗？
  目前解决是使用多次重试，但是没法用上分片下载的功能，线程中调用方法失败只能整个文件重新下载
