### ISSUE TITLE
Python3.7 put_object 返回 403 SignatureDoesNotMatch

### ISSUE THREAD

**Issue by hegwin** [aliyun/aliyun-oss-python-sdk#186]
Python version: 3.7.3

oss2.__version__ 2.6.1

Code:

```python
auth = oss2.Auth(access_key_id, access_key_secret)
bucket = oss2.Bucket(auth, 'https://oss-cn-shanghai.aliyuncs.com', bucket_name)
bucket.put_object(filename, json_str)
```

Result:

```
oss2.exceptions.SignatureDoesNotMatch: {'status': 403, 'x-oss-request-id': '5D031A3CA4DF8D178D3D499B', 'details': {'Code': 'SignatureDoesNotMatch', 'Message': 'The request signature we calculated does not match the signature you provided. Check your key and signing method.', 'RequestId': '5D031A3CA4DF8D178D3D499B', 'HostId': '', 'OSSAccessKeyId': 'LTAIpgksvlLgcdSE', 'SignatureProvided': 'sJEE6UN2s5CfTEQVmW97SV71UX8=', 'StringToSign': 'PUT\n\napplication/json\nFri, 14 Jun 2019 03:53:30 GMT\n/*****/locations.json', 'StringToSignBytes': '50 55 54 0A 0A 61 70 70 6C 69 63 61 74 69 6F 6E 2F 6A 73 6F 6E 0A 46 72 69 2C 20 31 34 20 4A 75 6E 20 32 30 31 39 20 30 33 3A 35 33 3A 33 30 20 47 4D 54 0A 2F 77 65 77 6F 72 6B 2D 72 65 64 73 68 69 66 74 2D 64 61 74 61 2D 74 72 61 6E 73 66 65 72 2F 6C 6F 63 61 74 69 6F 6E 73 2E 6A 73 6F 6E ‘}}


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in upload_to_oss
  File "/usr/local/lib/python3.7/site-packages/oss2/api.py", line 456, in put_object
    resp = self.__do_object('PUT', key, data=data, headers=headers)
  File "/usr/local/lib/python3.7/site-packages/oss2/api.py", line 1590, in __do_object
    return self._do(method, self.bucket_name, key, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/oss2/api.py", line 210, in _do
    raise e
```

这是已知的问题吗？还是目前还不支持Python3.7？

**Comment by hegwin** [comment]
我重新生成了access_key_id和access_key_secret就恢复了，这样看来不是Python客户端版本的问题。

只是目前报错是 `SignatureDoesNotMatch` ，和我实际情况“Access Invalid”不太符合。

**Comment by hangzws** [comment]
@hegwin OSS权限检验使用签名机制，不会将access_key_secret等敏感信息上传网络，因此在access_key_secret写错时，无法判断是否是access_key_secret出错还是其他原因导致签名错误。下次出现这种问题，你可以将python sdk的日志级别打开到debug级别，比较客户端生成的签名字符串和服务端生成的签名字符串是否匹配，如果有问题，可以联系我们。
