### ISSUE TITLE
python 3.7 import oss2 直接报错

### ISSUE THREAD

**Issue by chuanxinwong** [aliyun/aliyun-oss-python-sdk#188]
`
# test.py

import oss2

print("aaa")
`

报错如下：

`
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import oss2
  File "C:\Users\cxw\AppData\Roaming\Python\Python37\site-packages\oss2\__init__.py", line 3, in <module>
    from . import models, exceptions
  File "C:\Users\cxw\AppData\Roaming\Python\Python37\site-packages\oss2\models.py", line 10, in <module>
    from .utils import http_to_unixtime, make_progress_adapter, make_crc_adapter
  File "C:\Users\cxw\AppData\Roaming\Python\Python37\site-packages\oss2\utils.py", line 30, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\cxw\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\cxw\AppData\Roaming\Python\Python37\site-packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\cxw\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': cannot load library 'C:\Users\cxw\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\..\Cipher\_raw_ecb.cp37-win_amd64.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to loca
te a library called 'C:\\Users\\cxw\\AppData\\Roaming\\Python\\Python37\\site-packages\\Crypto\\Util\\..\\Cipher\\_raw_ecb.cp37-win_amd64.pyd', Trying '_raw_ecb.pyd': cannot load library 'C:\Users\cxw\AppData\Roaming\Python\Python37\site-packages\Crypto\Util\..\Cipher\_raw_ecb.pyd': error 0x7e.  Additional
ly, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\cxw\\AppData\\Roaming\\Python\\Python37\\site-packages\\Crypto\\Util\\..\\Cipher\\_raw_ecb.pyd'

`

**Comment by zcheneng** [comment]
解决了么？

**Comment by Liangkz** [comment]
![image](https://user-images.githubusercontent.com/49154802/108974517-7db8e600-76c0-11eb-80e3-f6ed3706853b.png)

**Comment by frank-pian** [comment]
3.5.7也有同样问题

**Comment by wxl24life** [comment]
> 解决了么？

看上去已经解决了

Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

import oss2
print('test')
test
