### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by ljf1239848066** [aliyun/aliyun-oss-python-sdk#212]
Python 2.7.10 (default, Jul 17 2015, 00:40:43) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import oss2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/oss2/__init__.py", line 3, in <module>
    from . import models, exceptions
  File "/usr/local/lib/python2.7/site-packages/oss2/models.py", line 13, in <module>
    from .select_response import SelectResponseAdapter
  File "/usr/local/lib/python2.7/site-packages/oss2/select_response.py", line 3, in <module>
    import requests
ImportError: No module named requests

**Comment by ljf1239848066** [comment]
1. install oss2 by pip
2. check python version in OS, note the possible version difference between `/bin/usr/python`、`python`、`python2`、`python3` after several upgrades.
