### ISSUE TITLE
最新版本2.11.0没有添加依赖six，导致加载失败

### ISSUE THREAD

**Issue by awong1900** [aliyun/aliyun-oss-python-sdk#240]
```
jump@wangtengdeMBP actions-runner % python            
Python 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import oss2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/oss2/__init__.py", line 3, in <module>
    from . import models, exceptions, defaults
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/oss2/models.py", line 9, in <module>
    from . import utils
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/oss2/utils.py", line 29, in <module>
    import abc, six
ModuleNotFoundError: No module named 'six'
>>> 
```

**Comment by awong1900** [comment]
导致我的action CI突然用不了。

**Comment by huiguangjun** [comment]
请更新到 2.12.1

**Comment by awong1900** [comment]
Oye
