### ISSUE TITLE
object_exists raise ServerError if object not exists

### ISSUE THREAD

**Issue by amarese** [aliyun/aliyun-oss-python-sdk#241]
>>> bucket.object_exists("file")
Exception: {'status': 404, 'x-oss-request-id': 'XXX', 'details': {'Code': 'NotFound', 'Message': 'The file has not been found.', 'RequestId': 'XXX', 'HostId': 'oss.aliyun.com'}}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.6/site-packages/oss2/api.py", line 874, in object_exists
    self.get_object_meta(key)
  File "/home/user/.local/lib/python3.6/site-packages/oss2/api.py", line 857, in get_object_meta
    resp = self.__do_object('GET', key, params={'objectMeta': ''})
  File "/home/user/.local/lib/python3.6/site-packages/oss2/api.py", line 1590, in __do_object
    return self._do(method, self.bucket_name, key, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/oss2/api.py", line 210, in _do
    raise e
oss2.exceptions.ServerError: {'status': 404, 'x-oss-request-id': 'XXX', 'details': {'Code': 'NotFound', 'Message': 'The file has not been found.', 'RequestId': 'XXX', 'HostId': 'oss.aliyun.com'}}

I wonder this is expected Error. I just want returned "False"

**Comment by snowrry** [comment]
Recommend to change the log level from info to debug when http response is not 2xx. 
oss2/api.py  line 230 and 247.
